version: '3.9'

services:
  server-app:
    image: 'zabbix/zabbix-server-pgsql:6.4-alpine-latest'
    container_name: 'zabbix-server-app'
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_zabbix
    networks:
      - zabbix-server-net
    depends_on:
      - db

  frontend-app:
    image: 'zabbix/zabbix-web-apache-pgsql:6.4-alpine-latest'
    container_name: 'zabbix-frontend-app'
    environment:
      - ZBX_SERVER_HOST=zabbix-server-app
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_zabbix
    networks:
      - zabbix-server-net
    depends_on:
      - db
      - server-app
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'curl', '-fs', 'http://localhost:8080' ]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 10s

  db:
    image: 'postgres:15.2-alpine3.17'
    container_name: 'zabbix-db'
    volumes:
      - '/home/yramon/Develop/zabbix-deployer/psql:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_zabbix
    networks:
      - zabbix-server-net
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U root', '-d $$POSTGRES_DB' ]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 10s

networks:
  zabbix-server-net:
    name: 'zabbix-server-net'
    ipam:
      driver: default
      config:
        - subnet: '172.18.0.0/28'
