version: '3.9'

services:
  server_app:
    image: zabbix/zabbix-server-pgsql:6.4.4-alpine 
    environment:
      - DB_SERVER_HOST=zabbix_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_zabbix
    networks:
      - zabbix-server-net
      - reverse-proxy
    depends_on:
      - db
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s

  frontend_app:
    image: zabbix/zabbix-web-apache-pgsql:6.4.4-alpine 
    environment:
      - ZBX_SERVER_HOST=zabbix_server_app
      - DB_SERVER_HOST=zabbix_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_zabbix
      - PHP_TZ=America/Maceio
    networks:
      - zabbix-server-net
      - reverse-proxy
    depends_on:
      - db
      - server-app
    healthcheck:
      test: [ 'CMD', 'curl', '-fsI', 'http://localhost:8080' ]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 10s
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s

  db:
    image: postgres:15.2-alpine3.17
    volumes:
      - '/var/lib/zabbix-db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_zabbix
    networks:
      - zabbix-server-net
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U root', '-d $$POSTGRES_DB' ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s


  grafana_app:
    image: grafana/grafana:10.0.2
    networks:
      - zabbix-server-net
      - reverse-proxy
    user: '1024:1024'
    volumes:
      - '/var/lib/grafana-data:/var/lib/grafana'
    healthcheck:
      test: [ 'CMD', 'curl', '-fsI', 'http://localhost:3000' ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s


networks:
  zabbix-server-net:
    name: 'zabbix-server-net'
    ipam:
      driver: default
      config:
        - subnet: '172.23.6.0/28'

  reverse-proxy:
    name: nginx-proxymng-net
    external: true
