version: '3.9'

services:
  server_app:
    image: zabbix/zabbix-server-pgsql:6.4.4-alpine 
    environment:
      - DB_SERVER_HOST=zabbix_db
      - POSTGRES_USER_FILE=/run/secrets/zbxsec-db-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/zbxsec-dbuser-passwd
      - POSTGRES_DB=
    networks:
      - zabbix-server-net
    secrets:
      - source: zbxsec-db-user
        target: zbxsec-db-user
        mode: 0440
      - source: zbxsec-dbuser-passwd
        target: zbxsec-dbuser-passwd
        mode: 0440 
    depends_on:
      - zabbix_db
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s

  frontend_app:
    image: zabbix/zabbix-web-apache-pgsql:6.4.4-alpine 
    environment:
      - ZBX_SERVER_HOST=zabbix_server_app
      - DB_SERVER_HOST=zabbix_db
      - POSTGRES_USER_FILE=/run/secrets/zbxsec-db-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/zbxsec-dbuser-passwd
      - POSTGRES_DB=
      - PHP_TZ=America/Maceio
    networks:
      - zabbix-server-net
      - reverse-proxy
    secrets:
      - source: zbxsec-db-user
        target: zbxsec-db-user
        mode: 0440
      - source: zbxsec-dbuser-passwd
        target: zbxsec-dbuser-passwd
        mode: 0440
    depends_on:
      - zabbix_db
      - zabbix_server_app
    healthcheck:
      test: [ 'CMD', 'curl', '-fsI', 'http://localhost:8080' ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s

  db:
    image: postgres:15.2-alpine3.17
    volumes:
      - /$(pwd)/zabbix-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER_FILE=/run/secrets/zbxsec-db-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/zbxsec-dbuser-passwd
      - POSTGRES_DB=
    networks:
      - zabbix-server-net
    secrets:
      - source: zbxsec-db-user
        target: zbxsec-db-user
        mode: 0440
      - source: zbxsec-dbuser-passwd
        target: zbxsec-dbuser-passwd
        mode: 0440 
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U root', '-d $$POSTGRES_DB' ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s


  grafana_app:
    image: grafana/grafana:10.0.2
    networks:
      - zabbix-server-net
      - reverse-proxy
    user: '1024:1024'
    volumes:
      - /$(pwd)/grafana-data:/var/lib/grafana
    healthcheck:
      test: [ 'CMD', 'curl', '-fsI', 'http://localhost:3000' ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s

secrets:
  zbxsec-db-user:
    external: true
  zbxsec-dbuser-passwd:
    external: true

networks:
  zabbix-server-net:
    name: zabbix-server-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28

  reverse-proxy:
    name: reverse-proxy
    external: true
